# -*- coding: utf-8 -*-
"""Salinan dari Salinan dari Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmv7bmFRpINoCZX_1u4HFOq2KiBE_2HW

1. Loading and Displaying Well Data From CSV
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

filename = list(uploaded.keys())[0]

well = pd.read_csv(filename, header=0)
#L0509WellData.csv

well.head()

well.describe()

well.replace(-999, np.nan, inplace=True)

well.describe()

well.head()

well.head(20)

well.plot(x = 'DEPTH', y = 'GR')

well.plot(kind = 'scatter', x = 'NPHI', y = 'RHOB', ylim=(3, 2))

well.plot(kind = 'scatter', x = 'NPHI', y = 'RHOB', c='GR',
          colormap='jet',
          ylim=(3, 2))

well['GR'].plot(kind="hist", bins = 30)

well['GR'].plot(kind="kde", xlim =(0,200))

"""2. Displaying a Well Plot with Matplotlib"""

import matplotlib.pyplot as plt

fig = plt.subplots(figsize=(10,10))

#Set up the plot axes
ax1 = plt.subplot2grid((1,3), (0,0), rowspan=1, colspan = 1)
ax2 = plt.subplot2grid((1,3), (0,1), rowspan=1, colspan = 1)
ax3 = plt.subplot2grid((1,3), (0,2), rowspan=1, colspan = 1)

ax1.plot("GR", "DEPTH", data = well, color = "green") # Call the data from the well dataframe
ax1.set_title("Gamma") # Assign a track title
ax1.set_xlim(0, 200) # Change the limits for the curve being plotted
ax1.set_ylim(4850, 4600) # Set the depth range
ax1.grid() # Display the grid

ax2.plot("RHOB", "DEPTH", data = well, color = "red")
ax2.set_title("Density")
ax2.set_xlim(1.95, 2.95)
ax2.set_ylim(4850, 4600)
ax2.grid()

ax3.plot("DT", "DEPTH", data = well, color = "purple")
ax3.set_title("Sonic")
ax3.set_xlim(140, 40)
ax3.set_ylim(4850, 4600)
ax3.grid()

fig, ax = plt.subplots(figsize=(10,10))

#Set up the plot axes
ax1 = plt.subplot2grid((1,3), (0,0), rowspan=1, colspan = 1)
ax2 = plt.subplot2grid((1,3), (0,1), rowspan=1, colspan = 1)
ax3 = plt.subplot2grid((1,3), (0,2), rowspan=1, colspan = 1)
ax4 = ax2.twiny() #Twins the y-axis for the density track with the neutron track

# As our curve scales will be detached from the top of the track,
# this code adds the top border back in without dealing with splines
ax7 = ax1.twiny()
ax7.xaxis.set_visible(False)
ax8 = ax2.twiny()
ax8.xaxis.set_visible(False)
ax9 = ax3.twiny()
ax9.xaxis.set_visible(False)

# Gamma Ray track
ax1.plot("GR", "DEPTH", data = well, color = "green")
ax1.set_xlabel("Gamma")
ax1.xaxis.label.set_color("green")
ax1.set_xlim(0, 200)
ax1.set_ylabel("Depth (m)")
ax1.tick_params(axis='x', colors="green")
ax1.spines["top"].set_edgecolor("green")
ax1.title.set_color('green')
ax1.set_xticks([0, 50, 100, 150, 200])

# Density track
ax2.plot("RHOB", "DEPTH", data = well, color = "red")
ax2.set_xlabel("Density")
ax2.set_xlim(1.95, 2.95)
ax2.xaxis.label.set_color("red")
ax2.tick_params(axis='x', colors="red")
ax2.spines["top"].set_edgecolor("red")
ax2.set_xticks([1.95, 2.2, 2.45, 2.7, 2.95])

# Sonic track
ax3.plot("DT", "DEPTH", data = well, color = "purple")
ax3.set_xlabel("Sonic")
ax3.set_xlim(140, 40)
ax3.xaxis.label.set_color("purple")
ax3.tick_params(axis='x', colors="purple")
ax3.spines["top"].set_edgecolor("purple")

# Neutron track placed ontop of density track
ax4.plot("NPHI", "DEPTH", data = well, color = "blue")
ax4.set_xlabel('Neutron')
ax4.xaxis.label.set_color("blue")
ax4.set_xlim(0.45, -0.15)
ax4.set_ylim(4850, 4600)
ax4.tick_params(axis='x', colors="blue")
ax4.spines["top"].set_position(("axes", 1.08))
ax4.spines["top"].set_visible(True)
ax4.spines["top"].set_edgecolor("blue")
ax4.set_xticks([0.45, 0.3, 0.15,0, -0.15])

# Common functions for setting up the plot can be extracted into
# a for loop. This saves repeating code.
for ax in [ax1, ax2, ax3]:
    ax.set_ylim(4850, 4600)
    ax.grid(which='major', color='lightgrey', linestyle='-')
    ax.xaxis.set_ticks_position("top")
    ax.xaxis.set_label_position("top")
    ax.spines["top"].set_position(("axes", 1.02))


plt.tight_layout()

"""3. Displaying Histograms and Crossplots"""

mean = well['GR'].mean()
p5 = well['GR'].quantile(0.05)
p95 = well['GR'].quantile(0.95)

plt.figure(figsize=(6,4), dpi=300)
well['GR'].plot(kind='hist', bins=30, color='red', alpha=0.5, edgecolor='black')
plt.xlabel('Gamma Ray', fontsize=14)
plt.ylabel('Frequency', fontsize=14)
plt.xlim(0,200)

plt.axvline(mean, color='blue', label='mean')
plt.axvline(p5, color='green', label='5th Percentile')
plt.axvline(p95, color='purple', label='95th Percentile')

plt.legend()
plt.show()

well.hist(column="GR")

well.hist(column="GR", bins = 30)

well.hist(column="GR", bins = 30, alpha = 0.5)

cols_to_plot = list(well)

cols_to_plot.remove("DEPTH")

#Setup the number of rows and columns for our plot
rows = 3
cols = 2

fig=plt.figure(figsize=(10,10))

for i, feature in enumerate(cols_to_plot):
    ax=fig.add_subplot(rows,cols,i+1)
    well[feature].hist(bins=20,ax=ax,facecolor='green', alpha=0.6)
    ax.set_title(feature+" Distribution")
    ax.set_axisbelow(True)
    ax.grid(color='whitesmoke')

plt.tight_layout()
plt.show()

well.plot(kind="scatter", x="NPHI", y="RHOB", c="GR",
          colormap="YlOrRd_r", ylim=(3,2))

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(5,5))
ax = fig.add_subplot(111, projection="3d")

ax.scatter(well["NPHI"], well["RHOB"], well["GR"], alpha= 0.3, c="r")

fig, ax = plt.subplots(figsize=(10,10))

ax1 = plt.subplot2grid((2,2), (0,0), rowspan=1, colspan=1)
ax2 = plt.subplot2grid((2,2), (0,1), rowspan=1, colspan=1)
ax3 = plt.subplot2grid((2,2), (1,0), rowspan=1, colspan=1)
ax4 = plt.subplot2grid((2,2), (1,1), rowspan=1, colspan=1)

ax1.scatter(x= "NPHI", y= "RHOB", data= well, marker="s", alpha= 0.2)
ax1.set_ylim(3, 1.8)
ax1.set_ylabel("RHOB (g/cc)")
ax1.set_xlabel("NPHI (dec)")


ax2.scatter(x= "GR", y= "RHOB", data= well, marker="p", alpha= 0.2)
ax1.set_ylim(3, 1.8)
ax2.set_ylabel("RHOB (g/cc)")
ax2.set_xlabel("GR (API)")

ax3.scatter(x= "DT", y= "RHOB", data= well, marker="*", alpha= 0.2)
ax3.set_ylim(3, 1.8)
ax3.set_ylabel("RHOB (g/cc)")
ax3.set_xlabel("DT (us/ft)")

ax4.scatter(x= "GR", y= "DT", data= well, marker="D", alpha= 0.2)
ax4.set_ylabel("DT (us/ft)")
ax4.set_xlabel("GR (API)")


plt.tight_layout()

"""4. Displaying Core Data and Deriving a Poro Perm Relationship"""

uploaded = files.upload()

filename = list(uploaded.keys())[0]

core_data = pd.read_csv(filename, na_values=[' ', -999.25])
#15_9-19A-CORE.csv

core_data.head()

core_data.describe()

core_data.plot(kind="scatter", x="CPOR", y="CKHG")

core_data.plot(kind="scatter", x="CPOR", y="CKHG")
plt.yscale('log')
plt.grid(True)

from matplotlib.ticker import FuncFormatter
fig, ax = plt.subplots()

ax.axis([0, 40, 0.01, 100000])
ax.plot(core_data['CPOR'], core_data['CKHG'], 'bo')
ax.set_yscale('log')
ax.grid(True)
ax.set_ylabel('Core Perm (mD)')
ax.set_xlabel('Core Porosity (%)')

#Format the axes so that they show whole numbers
for axis in [ax.yaxis, ax.xaxis]:
    formatter = FuncFormatter(lambda y, _: '{:.16g}'.format(y))
    axis.set_major_formatter(formatter)

import statsmodels.api as sm

x = core_data['CPOR']
y = np.log10(core_data['CKHG'])

model = sm.OLS(y, x, missing='drop')
results = model.fit()

results.summary()

x = np.polyfit(core_data['CPOR'], np.log10(core_data['CKHG']), 1)

x

from matplotlib.ticker import FuncFormatter
fig, ax = plt.subplots()

ax.axis([0, 30, 0.01, 10000])
ax.semilogy(core_data['CPOR'], core_data['CKH'], 'bo')

ax.grid(True)
ax.set_ylabel('Core Perm (mD)')
ax.set_xlabel('Core Porosity (%)')

ax.semilogy(core_data['CPOR'], 10**(x[0] * core_data['CPOR'] + x[1]), 'r-')


#Format the axes so that they show whole numbers
for axis in [ax.yaxis, ax.xaxis]:
    formatter = FuncFormatter(lambda y, _: '{:.16g}'.format(y))
    axis.set_major_formatter(formatter)

core_data["PRED_PERM"] = 10**(x[0] * core_data['CPOR'] + x[1])

core_data.describe()

fig, ax = plt.subplots()

ax.axis([0.01, 10000, 0.01, 10000])
ax.loglog(core_data['CKH'], core_data['PRED_PERM'], 'bo')
ax.loglog([0.01, 10000], [0.01, 10000], 'r-')

"""Unsupervised Clustering on Well Log Data"""

import seaborn as sns
import matplotlib.colors as colors

uploaded = files.upload()

filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)
#xeek_train_subset.csv

df.describe()

df.columns

workingdf = df[["WELL", "DEPTH_MD", "RDEP", "RHOB", "GR", "NPHI", "PEF", "DTC", "FORCE_2020_LITHOFACIES_LITHOLOGY"]].copy()

workingdf.rename(columns={'FORCE_2020_LITHOFACIES_LITHOLOGY':'FACIES'}, inplace=True)

workingdf

lithology_numbers = {30000: 'Sandstone',
                 65030: 'Sandstone/Shale',
                 65000: 'Shale',
                 80000: 'Marl',
                 74000: 'Dolomite',
                 70000: 'Limestone',
                 70032: 'Chalk',
                 88000: 'Halite',
                 86000: 'Anhydrite',
                 99000: 'Tuff',
                 90000: 'Coal',
                 93000: 'Basement'}

simple_lithology_numbers = {30000: 1,
                 65030: 2,
                 65000: 3,
                 80000: 4,
                 74000: 5,
                 70000: 6,
                 70032: 7,
                 88000: 8,
                 86000: 9,
                 99000: 10,
                 90000: 11,
                 93000: 12}

workingdf['LITH'] = workingdf['FACIES'].map(lithology_numbers)

workingdf['LITH_SI'] = workingdf['FACIES'].map(simple_lithology_numbers)

workingdf

g = sns.FacetGrid(workingdf, col='LITH', col_wrap=4)
g.map(sns.scatterplot, 'NPHI', 'RHOB', alpha=0.5)
g.set(xlim=(-0.15, 1))
g.set(ylim=(3, 1))

def create_plot(wellname, dataframe, curves_to_plot, depth_curve, log_curves=[], facies_curves=[]):
    # Count the number of tracks we need
    num_tracks = len(curves_to_plot)

    facies_color = ['#F4D03F', '#F5B041','#DC7633','#6E2C00', '#1B4F72','#2E86C1', '#AED6F1', '#A569BD', '#196F3D', 'red','black', 'blue']


    # Setup the figure and axes
    fig, ax = plt.subplots(nrows=1, ncols=num_tracks, figsize=(num_tracks*2, 10))

    # Create a super title for the entire plot
    fig.suptitle(wellname, fontsize=20, y=1.05)

    # Loop through each curve in curves_to_plot and create a track with that data
    for i, curve in enumerate(curves_to_plot):
        if curve in facies_curves:
            cmap_facies = colors.ListedColormap(facies_color[0:dataframe[curve].max()], 'indexed')

            cluster=np.repeat(np.expand_dims(dataframe[curve].values,1), 100, 1)
            im=ax[i].imshow(cluster, interpolation='none', cmap=cmap_facies, aspect='auto',vmin=dataframe[curve].min(),vmax=dataframe[curve].max(),
                            extent=[0,20, depth_curve.max(), depth_curve.min()])

#             for key in lithology_setup.keys():
#                 color = lithology_setup[key]['color']
#                 ax[i].fill_betweenx(depth_curve, 0, dataframe[curve].max(),
#                                   where=(dataframe[curve]==key),
#                                   facecolor=color)
#
        else:
            ax[i].plot(dataframe[curve], depth_curve)


        # Setup a few plot cosmetics
        ax[i].set_title(curve, fontsize=14, fontweight='bold')
        ax[i].grid(which='major', color='lightgrey', linestyle='-')

        # We want to pass in the deepest depth first, so we are displaying the data
        # from shallow to deep
        ax[i].set_ylim(depth_curve.max(), depth_curve.min())
#         ax[i].set_ylim(3500, 3000)

        # Only set the y-label for the first track. Hide it for the rest
        if i == 0:
            ax[i].set_ylabel('DEPTH (m)', fontsize=18, fontweight='bold')
        else:
            plt.setp(ax[i].get_yticklabels(), visible = False)

        # Check to see if we have any logarithmic scaled curves
        if curve in log_curves:
            ax[i].set_xscale('log')
            ax[i].grid(which='minor', color='lightgrey', linestyle='-')



    plt.tight_layout()
    plt.show()

    return cmap_facies

def well_splitter(dataframe, groupby_column):
    grouped = dataframe.groupby(groupby_column)

    # Create empty lists
    wells_as_dfs = []
    wells_wellnames = []

    #Split up the data by well
    for well, data in grouped:
        wells_as_dfs.append(data)
        wells_wellnames.append(well)

    print('index  wellname')
    for i, name in enumerate(wells_wellnames):
        print(f'{i}      {name}')

    return wells_as_dfs, wells_wellnames

grouped_wells, grouped_names = well_splitter(workingdf, 'WELL')

from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

def optimise_k_means(data, max_k):
    means = []
    inertias = []

    for k in range(1,max_k):
        kmeans = KMeans(n_clusters=k)
        kmeans.fit(data)
        means.append(k)
        inertias.append(kmeans.inertia_)

    fig = plt.subplots(figsize=(10, 5))
    plt.plot(means, inertias, 'o-')
    plt.xlabel("Number of Clusters")
    plt.ylabel("Inertia")
    plt.grid(True)
    plt.show()

from yellowbrick.cluster import SilhouetteVisualizer

def visualise_k_means_sillouette(data, max_k):
    fig, ax = plt.subplots(2, 3, figsize=(10, 5))
    means = []
    silhouette_avg = []

    for k in range(2,max_k): #start at 2 clusters
        print(k)
        kmeans = KMeans(n_clusters=k)
        q, mod = divmod(k, 2)

        vis = SilhouetteVisualizer(kmeans, colors='yellowbrick', ax=ax[q-1][mod])
        vis.fit(data)

    # plt.plot(means, inertias, 'o-')
    # plt.xlabel("Number of Clusters")
    # plt.ylabel("Inertia")
    # plt.grid(True)
    # plt.show()

data = workingdf[['GR', 'RHOB', 'NPHI', 'DTC']]
kmeans = KMeans(n_clusters=10)
visualizer = SilhouetteVisualizer(kmeans, colors='yellowbrick')
visualizer.fit(data)
visualizer.show()

from sklearn.metrics import silhouette_score

def optimise_k_means_sillouette(data, max_k):
    means = []
    silhouette_avg = []

    range_n_clusters = [2, 3, 4, 5, 6, 7, 8]
    silhouette_avg = []
    for num_clusters in range_n_clusters:

        # initialise kmeans
        kmeans = KMeans(n_clusters=num_clusters)
        kmeans.fit(data)
        cluster_labels = kmeans.labels_

        # silhouette score
        silhouette_avg.append(silhouette_score(data, cluster_labels))
    plt.plot(range_n_clusters,silhouette_avg, 'bo-')
    plt.xlabel("Number of Clusters")
    plt.ylabel('Silhouette Score')
    plt.title('Silhouette Analysis For Kmeans', fontsize=14, fontweight='bold')
    plt.show()

optimise_k_means_sillouette(workingdf[['GR', 'RHOB', 'NPHI', 'DTC']], 5)

workingdf.dropna(inplace=True)

workingdf.describe()

optimise_k_means(workingdf[['GR', 'RHOB', 'NPHI', 'DTC']], 30)

# Create the KMeans model with the selected number of clusters
kmeans = KMeans(n_clusters=5)

# Fit the model to our dataset
kmeans.fit(workingdf[['GR', 'RHOB', 'NPHI', 'DTC']])

# Assign the data back to the workingdf
workingdf['KMeans'] = kmeans.labels_

# Create the gmm model with the selected number of clusters/components
gmm = GaussianMixture(n_components=5)

# Fit the model to our dataset
gmm.fit(workingdf[['GR', 'RHOB', 'NPHI', 'DTC']])

# Predict the labels
gmm_labels = gmm.predict(workingdf[['GR', 'RHOB', 'NPHI', 'DTC']])

# Assign the labels back to the workingdf
workingdf['GMM'] = gmm_labels

dfs_wells, wellnames = well_splitter(workingdf, 'WELL')

# Setup the curves to plot
curves_to_plot = ['GR', 'RHOB', 'NPHI', 'DTC',  'LITH_SI', 'KMeans','GMM']
logarithmic_curves = ['RDEP']
facies_curve=['KMeans','GMM', 'LITH_SI']

# Create plot by passing in the relevant well index number
well = 4
cmap_facies = create_plot(wellnames[well],
            dfs_wells[well],
            curves_to_plot,
            dfs_wells[well]['DEPTH_MD'],
            logarithmic_curves, facies_curve)

fig, ax = plt.subplots(figsize=(20,10))
ax1 = plt.subplot2grid((1,3), (0,0))
ax1.scatter(dfs_wells[well]['NPHI'], dfs_wells[well]['RHOB'], c=dfs_wells[well]['KMeans'], s=8, cmap=cmap_facies)
ax1.set_title('KMeans', fontsize=22, y=1.05)

ax2 = plt.subplot2grid((1,3), (0,1))
ax2.scatter(dfs_wells[well]['NPHI'], dfs_wells[well]['RHOB'], c=dfs_wells[well]['GMM'], s=8)
ax2.set_title('GMM', fontsize=22, y=1.05)

ax3 = plt.subplot2grid((1,3), (0,2))
ax3.scatter(dfs_wells[well]['NPHI'], dfs_wells[well]['RHOB'], c=dfs_wells[well]['LITH_SI'], s=8)
ax3.set_title('Lithology (Supplied)', fontsize=22, y=1.05)

for ax in [ax1, ax2, ax3]:
    ax.set_xlim(0, 0.7)
    ax.set_ylim(3, 1.5)
    ax.set_ylabel('RHOB', fontsize=18, labelpad=30)
    ax.set_xlabel('NPHI', fontsize=18, labelpad=30)
    ax.grid()
    ax.set_axisbelow(True)

    ax.tick_params(axis='both', labelsize=14)
plt.tight_layout()

sns.pairplot(dfs_wells[4], vars=['GR', 'RHOB','NPHI', 'DTC'], hue='KMeans', palette='Dark2',
             diag_kind='kde', plot_kws = {'s': 15, 'marker':'o', 'alpha':1})

sns.pairplot(dfs_wells[4], vars=['GR', 'RHOB','NPHI', 'DTC'], hue='GMM', palette='Dark2',
             diag_kind='kde', plot_kws = {'s': 15, 'marker':'o', 'alpha':1})

